apiVersion: v1
description: helm chart for xwiki
name: xwiki
version: 11.stable
appVersion: 11-stable
description: XWiki is a free wiki software platform written in Java with a design emphasis on extensibility. XWiki is an enterprise wiki. It includes WYSIWYG editing, OpenDocument based document import/export, semantic annotations and tagging, and advanced permissions management.
keywords:
- xwiki
home: http://xwiki.org
icon: hhttps://www.xwiki.org/xwiki/bin/download/Main/Logo/logo-x.png
sources:
- https://github.com/xwiki-contrib/docker-xwiki
- https://github.com/keyporttech/charts
maintainers:
- name: John Felten
  email: john@keyporttech.com
- name: John Felten
  email: john@keyporttech.com
