dependencies:
  - name: mysql
    repository: https://charts.helm.sh/stable
    version: 1.2.0
    condition: mysql.enabled
  - name: postgresql
    repository: https://charts.helm.sh/stable
    version: 5.3.7
    condition: postgresql.enabled
