# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: xwiki
  pullPolicy: IfNotPresent
## Image Tag useful when externalDB is been used
  tag: ''
service:
  portName: node
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 350m
    memory: 1000Mi
  requests:
    cpu: 150m
    memory: 250Mi
##
## MySql chart configuration
##
## https://github.com/helm/charts/tree/master/stable/mysql
##
mysql:
 ## Whether to deploy a mysql server. Set false for a different database.
  enabled: false
  mysqlRootPassword: xwiki
  mysqlUser: xwiki
  mysqlPassword: xwiki
  mysqlDatabase: xwiki
  imageTag: 5.7

##
## MySql chart configuration
##
## https://github.com/helm/charts/tree/master/stable/postgresql
##
postgresql:
 ## Whether to deploy a postgresql server. Set false for a different database.
  enabled: true
  postgresqlUsername: xwiki
  postgresqlPassword: xwiki
  postgresqlDatabase: xwiki
  image:
    tag: 11.3.0-debian-9-r38
  #persistence:
  #  size: 8Gi

##
## For custom mysql and postgres database. Use externalDB. 
## Would be used only if postgres and mysql is disabled.
## Set the image tag if want to use externalDB
##
externalDB:
  password: ''
  user: ''
  database: ''
  host: ''

##
## To use external solr enable solr, provide host and port
##
solr:
  enabled: false
  host: localhost
  port: 8983

# To use ingress for routing set ingress.enabled value to true and istio.enabled value to false
ingress:
  enabled: true
  issuer: dev-issuer
  annotations:
    kubernetes.io/ingress.class: nginx
    #   ingress.kubernetes.io/rewrite-target: /

# To use istio for routing set istio.enabled value to true and ingress.enabled value to false
istio:
  enabled: false
  host: "*"
storage: "500Mi"
storageClassName: ""
buildID: "123"


## Read about PostDistribution budget at https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
## Use only on a clustered setup
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1
