# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  # image.name -- image name
  name: xwiki
  # image.pullPolicy -- image name
  pullPolicy: IfNotPresent
  # image.tag -- image tag
  tag: 12.6.5
service:
  # service.portName -- name of the port
  portName: node
  # service.name -- service name
  name: http
  # service.type -- service type
  type: ClusterIP
  # service.externalPort -- external port name
  externalPort: 80
  # service.internal -- interal service port
  internalPort: 8080
resources:
  limits:
    # resource.limits.cpu -- xwiki container cpu limit
    cpu: 350m
    # resource.limits.memory -- xwiki container memory limit
    memory: 1000Mi
  requests:
    # resources.requests.cpu -- xwiki container cpu request
    cpu: 150m
    # resources.requests.memory -- xwiki container memory request
    memory: 250Mi
##
## MySql chart configuration
##
## https://github.com/helm/charts/tree/master/stable/mysql
##
mysql:
  # mysql.enabled -- Whether to deploy a mysql server. Set false for a different database.
  enabled: false
  mysqlRootPassword: xwiki
  mysqlUser: xwiki
  mysqlPassword: xwiki
  mysqlDatabase: xwiki
  imageTag: 5.7

##
## MySql chart configuration
##
## https://github.com/helm/charts/tree/master/stable/postgresql
##
postgresql:
  # postgresql.enabled -- Whether to deploy a postgresql server. Set false for a different database.
  enabled: true
  postgresqlUsername: xwiki
  postgresqlPassword: xwiki
  postgresqlDatabase: xwiki
  image:
    tag: 11.3.0-debian-9-r38
  # persistence:
  #  size: 8Gi

##
## For custom mysql and postgres database. Use externalDB.
## Would be used only if postgres and mysql is disabled.
## Set the image tag if want to use externalDB
##
externalDB:
  password: ''
  user: ''
  database: ''
  host: ''

# solr -- To use external solr enable solr, provide host and port
solr:
  enabled: false
  host: localhost
  port: 8983

# To use ingress for routing set ingress.enabled value to true and istio.enabled value to false
ingress:
  # ingress.enabled -- enable the ingress
  enabled: false
  # ingress.host -- ingress host name
  host: my-host
  # ingress.annotations -- ingress annotations
  annotations:
    kubernetes.io/ingress.class: nginx
    #   ingress.kubernetes.io/rewrite-target: /
  # ingress.tls -- tls config for ingress
  tls:
  # Secrets must be manually created in the namespace.
  - secretName: wiki-tls
    hosts:
      - myhost

# ishtio -- To use istio for routing set istio.enabled value to true and ingress.enabled value to false
istio:
  enabled: false
  host: "*"

## Read about PostDistribution budget at https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
## Use only on a clustered setup
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

# storageType -- type of storage for the volume: pvc, emptyDir or directVolume
storageType: emptyDir

# storageVolume -- is used by pvc and storage types
# storageVolume
