{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
    {{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
   - host: {{ .Values.service.http.externalHost }}
     http:
       paths:
       - pathType: Prefix
         path: /
         backend:
          service:
            name: {{ template "fullname" . }}
            port:
              number: {{ .Values.service.http.port }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}

{{- end -}}
